### ISSUE TITLE
[Ck][meal calendar][sub-task#1]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/types#11]
part of #10 task.
we have a list of static data from one of recipes based website.
we'll convert that data into static arrays, and later will use in our projects.
Sample of data, related to calendar + events you can see below.

https://github.com/GroceriStar/react-only-intern-23/blob/master/src/data/Data_WorkSceh.js

list of articles(basically we need data only from image)

- [ ] https://www.theresourcefulmama.com/meal-plan-week-5/
- [ ] https://www.theresourcefulmama.com/meal-planweek-4/
- [ ] https://www.theresourcefulmama.com/meal-planweek-3/
- [ ] https://www.theresourcefulmama.com/meal-plan-2/
- [ ] https://www.theresourcefulmama.com/meal-plan-week-1/

Please put your js arrays at this folder: https://github.com/GroceriStar/types/tree/master/MealCalendar

**Comment by LizTW** [comment]
All files have been posted for 1-5.  I think there needs to be some stable tags and labels for everything as I realized I was changing them as I was doing it....

**Comment by atherdon** [comment]
I think it looks perfect. this is what we need for now. closing it
