### ISSUE TITLE
[Ck][meal calendar][sub-task#2]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/types#12]
part of #10 task.
we have a list of static data from one of recipes based website.
we'll convert that data into static arrays, and later will use in our projects.
Sample of data, related to calendar + events you can see below.

https://github.com/GroceriStar/react-only-intern-23/blob/master/src/data/Data_WorkSceh.js

list of articles(basically we need data only from image)
- [x] https://www.theresourcefulmama.com/meal-plan-week-10/
- [x] https://www.theresourcefulmama.com/meal-planning-week-9/
- [x] https://www.theresourcefulmama.com/meal-planweek-8/
- [x] https://www.theresourcefulmama.com/meal-plan-week-6/
- [x] https://www.theresourcefulmama.com/2582/

Please put your js arrays at this folder: https://github.com/GroceriStar/types/tree/master/MealCalendar

**Comment by atherdon** [comment]
@MinkoJ2 this is task for you

**Comment by atherdon** [comment]
saw this?

**Comment by atherdon** [comment]
@MinkoJ2 please reply, because i'm not sure if you saw a notification for this issue

**Comment by atherdon** [comment]
@vadim9999 you can work on this task

**Comment by vadim9999** [comment]
https://github.com/GroceriStar/types/pull/24
@atherdon

**Comment by atherdon** [comment]
@vadim9999 perfect!
