### ISSUE TITLE
[Ck][meal calendar][sub-task#3]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/types#13]
part of #10 task.
we have a list of static data from one of recipes based website.
we'll convert that data into static arrays, and later will use in our projects.
Sample of data, related to calendar + events you can see below.

https://github.com/GroceriStar/react-only-intern-23/blob/master/src/data/Data_WorkSceh.js

list of articles(basically we need data only from image)

- [x] https://www.theresourcefulmama.com/meal-plan-week-11/
- [x] https://www.theresourcefulmama.com/meal-plan-week-12/
- [x] https://www.theresourcefulmama.com/meal-plan-week-13/
- [x] https://www.theresourcefulmama.com/meal-planning-week-14-2/
- [x] https://www.theresourcefulmama.com/meal-plan-week-15/

Please put your js arrays at this folder: https://github.com/GroceriStar/types/tree/master/MealCalendar

**Comment by atherdon** [comment]
@vadim9999 you can work on this task

**Comment by vadim9999** [comment]
@atherdon  
https://github.com/GroceriStar/types/pull/26

**Comment by atherdon** [comment]
done! closing
