### ISSUE TITLE
[Ck][meal calendar][sub-task#4]

### ISSUE THREAD

**Issue by atherdon** [GroceriStar/types#14]
part of #10 task.
we have a list of static data from one of recipes based website.
we'll convert that data into static arrays, and later will use in our projects.
Sample of data, related to calendar + events you can see below.

https://github.com/GroceriStar/react-only-intern-23/blob/master/src/data/Data_WorkSceh.js

list of articles(basically we need data only from image)

- [ ] https://www.theresourcefulmama.com/meal-planning-week-20/
- [ ] https://www.theresourcefulmama.com/meal-planning-week-19/
- [ ] https://www.theresourcefulmama.com/meal-planning-week-18/
- [ ] https://www.theresourcefulmama.com/meal-planning-week-17/
- [ ] https://www.theresourcefulmama.com/im-back-meal-planning-week-16/

Please put your js arrays at this folder: https://github.com/GroceriStar/types/tree/master/MealCalendar

**Comment by atherdon** [comment]
while i'm checking your pull request, you can work on this task @Yoimer

**Comment by Yoimer** [comment]
Sure, Let me check and I will pull my request.

**Comment by Yoimer** [comment]
Arthur, I added all the [Ck][meal calendar][sub-task#4]. Please check it out and let me know what you think. Please also check the previous pull request I made on this very same repo. Looking forward to hearing from you.
